/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSalahRouteImport } from './routes/_authenticated/salah'
import { Route as AuthenticatedQuranRouteImport } from './routes/_authenticated/quran'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedGratitudeRouteImport } from './routes/_authenticated/gratitude'
import { Route as AuthenticatedDhikrRouteImport } from './routes/_authenticated/dhikr'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalahRoute = AuthenticatedSalahRouteImport.update({
  id: '/salah',
  path: '/salah',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuranRoute = AuthenticatedQuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGratitudeRoute = AuthenticatedGratitudeRouteImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDhikrRoute = AuthenticatedDhikrRouteImport.update({
  id: '/dhikr',
  path: '/dhikr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dhikr': typeof AuthenticatedDhikrRoute
  '/gratitude': typeof AuthenticatedGratitudeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/quran': typeof AuthenticatedQuranRoute
  '/salah': typeof AuthenticatedSalahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dhikr': typeof AuthenticatedDhikrRoute
  '/gratitude': typeof AuthenticatedGratitudeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/quran': typeof AuthenticatedQuranRoute
  '/salah': typeof AuthenticatedSalahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dhikr': typeof AuthenticatedDhikrRoute
  '/_authenticated/gratitude': typeof AuthenticatedGratitudeRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/quran': typeof AuthenticatedQuranRoute
  '/_authenticated/salah': typeof AuthenticatedSalahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dhikr'
    | '/gratitude'
    | '/journal'
    | '/quran'
    | '/salah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dhikr'
    | '/gratitude'
    | '/journal'
    | '/quran'
    | '/salah'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dhikr'
    | '/_authenticated/gratitude'
    | '/_authenticated/journal'
    | '/_authenticated/quran'
    | '/_authenticated/salah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/salah': {
      id: '/_authenticated/salah'
      path: '/salah'
      fullPath: '/salah'
      preLoaderRoute: typeof AuthenticatedSalahRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quran': {
      id: '/_authenticated/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof AuthenticatedQuranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gratitude': {
      id: '/_authenticated/gratitude'
      path: '/gratitude'
      fullPath: '/gratitude'
      preLoaderRoute: typeof AuthenticatedGratitudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dhikr': {
      id: '/_authenticated/dhikr'
      path: '/dhikr'
      fullPath: '/dhikr'
      preLoaderRoute: typeof AuthenticatedDhikrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDhikrRoute: typeof AuthenticatedDhikrRoute
  AuthenticatedGratitudeRoute: typeof AuthenticatedGratitudeRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedQuranRoute: typeof AuthenticatedQuranRoute
  AuthenticatedSalahRoute: typeof AuthenticatedSalahRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDhikrRoute: AuthenticatedDhikrRoute,
  AuthenticatedGratitudeRoute: AuthenticatedGratitudeRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedQuranRoute: AuthenticatedQuranRoute,
  AuthenticatedSalahRoute: AuthenticatedSalahRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
